test:
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements-dev.txt
  - python3 -m pytest -vv
  - flake8 .
  - python3 -m pylint diceware --exit-zero
